In [1]:
import dask.dataframe as dd
from dask.distributed import Client
import pandas as pd
import numpy as np
from itertools import (takewhile,repeat)

# To replicate

1. Download NPPES: https://download.cms.gov/nppes/NPI_Files.html (Full Replacement Monthly NPI File
NPPES Data Dissemination (January 11, 2022) - ZIP format (836 MB))
        
2. Download https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/order-and-referring/data/january-31-2022

3. Move both CSV files to a `data` directory as above

4. Execute the following:

In [2]:
 def rawincount(filename):
    f = open(filename, 'rb')
    bufgen = takewhile(lambda x: x, (f.raw.read(1024*1024) for _ in repeat(None)))
    return sum( buf.count(b'\n') for buf in bufgen )

filename = '../data/npidata_pfile_20050523-20220109.csv'
df = dd.read_csv(filename)
df_shape = (rawincount(filename) - 1, len(df.columns))
print(f"Shape: {df_shape}")

Shape: (7147730, 330)

In [3]:
Client()

In [4]:
cms_nppes_df = dd.read_csv("../data/npidata_pfile_20050523-20220109.csv", low_memory=False,
 dtype={'Authorized Official Telephone Number': 'object',
       'Healthcare Provider Primary Taxonomy Switch_11': 'object',
       'Healthcare Provider Primary Taxonomy Switch_12': 'object',
       'Healthcare Provider Primary Taxonomy Switch_13': 'object',
       'Healthcare Provider Primary Taxonomy Switch_14': 'object',
       'Healthcare Provider Primary Taxonomy Switch_15': 'object',
       'Healthcare Provider Taxonomy Code_11': 'object',
       'Healthcare Provider Taxonomy Code_12': 'object',
       'Healthcare Provider Taxonomy Code_13': 'object',
       'Healthcare Provider Taxonomy Code_14': 'object',
       'Healthcare Provider Taxonomy Code_15': 'object',
       'Healthcare Provider Taxonomy Group_11': 'object',
       'Healthcare Provider Taxonomy Group_12': 'object',
       'Healthcare Provider Taxonomy Group_13': 'object',
       'Healthcare Provider Taxonomy Group_14': 'object',
       'Healthcare Provider Taxonomy Group_15': 'object',
       'Other Provider Identifier Issuer_16': 'object',
       'Other Provider Identifier Issuer_17': 'object',
       'Other Provider Identifier Issuer_18': 'object',
       'Other Provider Identifier Issuer_19': 'object',
       'Other Provider Identifier Issuer_20': 'object',
       'Other Provider Identifier Issuer_21': 'object',
       'Other Provider Identifier Issuer_22': 'object',
       'Other Provider Identifier Issuer_23': 'object',
       'Other Provider Identifier Issuer_24': 'object',
       'Other Provider Identifier Issuer_25': 'object',
       'Other Provider Identifier Issuer_26': 'object',
       'Other Provider Identifier Issuer_27': 'object',
       'Other Provider Identifier Issuer_28': 'object',
       'Other Provider Identifier Issuer_29': 'object',
       'Other Provider Identifier Issuer_30': 'object',
       'Other Provider Identifier Issuer_31': 'object',
       'Other Provider Identifier Issuer_32': 'object',
       'Other Provider Identifier Issuer_33': 'object',
       'Other Provider Identifier Issuer_34': 'object',
       'Other Provider Identifier Issuer_35': 'object',
       'Other Provider Identifier Issuer_36': 'object',
       'Other Provider Identifier Issuer_37': 'object',
       'Other Provider Identifier Issuer_39': 'object',
       'Other Provider Identifier Issuer_40': 'object',
       'Other Provider Identifier Issuer_41': 'object',
       'Other Provider Identifier Issuer_42': 'object',
       'Other Provider Identifier Issuer_43': 'object',
       'Other Provider Identifier Issuer_44': 'object',
       'Other Provider Identifier Issuer_45': 'object',
       'Other Provider Identifier Issuer_46': 'object',
       'Other Provider Identifier Issuer_47': 'object',
       'Other Provider Identifier Issuer_48': 'object',
       'Other Provider Identifier Issuer_49': 'object',
       'Other Provider Identifier State_16': 'object',
       'Other Provider Identifier State_17': 'object',
       'Other Provider Identifier State_18': 'object',
       'Other Provider Identifier State_19': 'object',
       'Other Provider Identifier State_20': 'object',
       'Other Provider Identifier State_21': 'object',
       'Other Provider Identifier State_22': 'object',
       'Other Provider Identifier State_23': 'object',
       'Other Provider Identifier State_24': 'object',
       'Other Provider Identifier State_25': 'object',
       'Other Provider Identifier State_26': 'object',
       'Other Provider Identifier State_27': 'object',
       'Other Provider Identifier State_28': 'object',
       'Other Provider Identifier State_29': 'object',
       'Other Provider Identifier State_30': 'object',
       'Other Provider Identifier State_31': 'object',
       'Other Provider Identifier State_32': 'object',
       'Other Provider Identifier State_33': 'object',
       'Other Provider Identifier State_34': 'object',
       'Other Provider Identifier State_35': 'object',
       'Other Provider Identifier State_36': 'object',
       'Other Provider Identifier State_37': 'object',
       'Other Provider Identifier State_38': 'object',
       'Other Provider Identifier State_39': 'object',
       'Other Provider Identifier State_47': 'object',
       'Other Provider Identifier State_48': 'object',
       'Other Provider Identifier_10': 'object',
       'Other Provider Identifier_13': 'object',
       'Other Provider Identifier_14': 'object',
       'Other Provider Identifier_15': 'object',
       'Other Provider Identifier_16': 'object',
       'Other Provider Identifier_17': 'object',
       'Other Provider Identifier_18': 'object',
       'Other Provider Identifier_19': 'object',
       'Other Provider Identifier_20': 'object',
       'Other Provider Identifier_21': 'object',
       'Other Provider Identifier_22': 'object',
       'Other Provider Identifier_23': 'object',
       'Other Provider Identifier_24': 'object',
       'Other Provider Identifier_25': 'object',
       'Other Provider Identifier_26': 'object',
       'Other Provider Identifier_27': 'object',
       'Other Provider Identifier_28': 'object',
       'Other Provider Identifier_29': 'object',
       'Other Provider Identifier_30': 'object',
       'Other Provider Identifier_32': 'object',
       'Other Provider Identifier_33': 'object',
       'Other Provider Identifier_37': 'object',
       'Other Provider Identifier_48': 'object',
       'Other Provider Identifier_49': 'object',
       'Provider Business Mailing Address Fax Number': 'object',
       'Provider Business Mailing Address Postal Code': 'object',
       'Provider Business Practice Location Address Fax Number': 'object',
       'Provider Business Practice Location Address Postal Code': 'object',
       'Provider Business Practice Location Address Telephone Number': 'object',
       'Provider License Number State Code_10': 'object',
       'Provider License Number State Code_11': 'object',
       'Provider License Number State Code_12': 'object',
       'Provider License Number State Code_13': 'object',
       'Provider License Number State Code_14': 'object',
       'Provider License Number State Code_15': 'object',
       'Provider License Number State Code_7': 'object',
       'Provider License Number_10': 'object',
       'Provider License Number_11': 'object',
       'Provider License Number_12': 'object',
       'Provider License Number_13': 'object',
       'Provider License Number_14': 'object',
       'Provider License Number_15': 'object',
       'Provider License Number_5': 'object',
       'Provider License Number_6': 'object',
       'Provider License Number_7': 'object',
       'Provider Other Name Suffix Text': 'object',
       'Other Provider Identifier State_40': 'object',
       'Other Provider Identifier State_41': 'object',
       'Other Provider Identifier State_42': 'object',
       'Other Provider Identifier State_43': 'object',
       'Other Provider Identifier State_44': 'object',
       'Other Provider Identifier State_45': 'object',
       'Other Provider Identifier State_46': 'object',
       'Other Provider Identifier_42': 'object',
       'Other Provider Identifier_44': 'object',
        'Other Provider Identifier_31': 'object',
       'Other Provider Identifier_34': 'object',
       'Other Provider Identifier_36': 'object',
        'Other Provider Identifier Issuer_38': 'object',
       'Other Provider Identifier Issuer_50': 'object',
       'Other Provider Identifier State_49': 'object',
       'Other Provider Identifier State_50': 'object',
       'Other Provider Identifier_35': 'object',
       'Other Provider Identifier_38': 'object',
       'Other Provider Identifier_43': 'object',
       'Other Provider Identifier_45': 'object',
       'Other Provider Identifier_50': 'object',
        'Other Provider Identifier_40': 'object',
        'Other Provider Identifier_41': 'object',
        'Other Provider Identifier_39': 'object',
        'Other Provider Identifier_46': 'object',
        'Other Provider Identifier_47': 'object',
'Authorized Official Credential Text': 'object',
       'Healthcare Provider Primary Taxonomy Switch_10': 'object',
       'Healthcare Provider Primary Taxonomy Switch_3': 'object',
       'Healthcare Provider Primary Taxonomy Switch_4': 'object',
       'Healthcare Provider Primary Taxonomy Switch_5': 'object',
       'Healthcare Provider Primary Taxonomy Switch_6': 'object',
       'Healthcare Provider Primary Taxonomy Switch_7': 'object',
       'Healthcare Provider Primary Taxonomy Switch_8': 'object',
       'Healthcare Provider Primary Taxonomy Switch_9': 'object',
       'Healthcare Provider Taxonomy Code_10': 'object',
       'Healthcare Provider Taxonomy Code_3': 'object',
       'Healthcare Provider Taxonomy Code_4': 'object',
       'Healthcare Provider Taxonomy Code_5': 'object',
       'Healthcare Provider Taxonomy Code_6': 'object',
       'Healthcare Provider Taxonomy Code_7': 'object',
       'Healthcare Provider Taxonomy Code_8': 'object',
       'Healthcare Provider Taxonomy Code_9': 'object',
       'Healthcare Provider Taxonomy Group_1': 'object',
       'Healthcare Provider Taxonomy Group_10': 'object',
       'Healthcare Provider Taxonomy Group_2': 'object',
       'Healthcare Provider Taxonomy Group_3': 'object',
       'Healthcare Provider Taxonomy Group_4': 'object',
       'Healthcare Provider Taxonomy Group_5': 'object',
       'Healthcare Provider Taxonomy Group_6': 'object',
       'Healthcare Provider Taxonomy Group_7': 'object',
       'Healthcare Provider Taxonomy Group_8': 'object',
       'Healthcare Provider Taxonomy Group_9': 'object',
       'NPI Reactivation Date': 'object',
       'Other Provider Identifier Issuer_10': 'object',
       'Other Provider Identifier Issuer_11': 'object',
       'Other Provider Identifier Issuer_12': 'object',
       'Other Provider Identifier Issuer_13': 'object',
       'Other Provider Identifier Issuer_14': 'object',
       'Other Provider Identifier Issuer_15': 'object',
       'Other Provider Identifier Issuer_6': 'object',
       'Other Provider Identifier Issuer_8': 'object',
       'Other Provider Identifier Issuer_9': 'object',
       'Other Provider Identifier State_10': 'object',
       'Other Provider Identifier State_11': 'object',
       'Other Provider Identifier State_12': 'object',
       'Other Provider Identifier State_13': 'object',
       'Other Provider Identifier State_14': 'object',
       'Other Provider Identifier State_15': 'object',
       'Other Provider Identifier State_8': 'object',
       'Other Provider Identifier State_9': 'object',
       'Other Provider Identifier_11': 'object',
       'Other Provider Identifier_12': 'object',
       'Other Provider Identifier_3': 'object',
       'Other Provider Identifier_4': 'object',
       'Other Provider Identifier_5': 'object',
       'Other Provider Identifier_7': 'object',
       'Other Provider Identifier_8': 'object',
       'Other Provider Identifier_9': 'object',
       'Parent Organization LBN': 'object',
       'Parent Organization TIN': 'object',
       'Provider Business Mailing Address Telephone Number': 'object',
       'Provider License Number State Code_3': 'object',
       'Provider License Number State Code_4': 'object',
       'Provider License Number State Code_5': 'object',
       'Provider License Number State Code_6': 'object',
       'Provider License Number State Code_8': 'object',
       'Provider License Number State Code_9': 'object',
       'Provider License Number_3': 'object',
       'Provider License Number_4': 'object',
       'Provider License Number_8': 'object',
       'Provider License Number_9': 'object',
       'Provider Name Suffix Text': 'object',
       'Provider Other Credential Text': 'object',
       'Provider Other First Name': 'object',
       'Provider Other Last Name': 'object',
       'Provider Other Middle Name': 'object',
       'Provider Other Name Prefix Text': 'object'        
       }, blocksize=25e6                    
    )

In [5]:
# weekly update (January 31, 2022)
all_order_and_referring_physicians = dd.read_csv("../data/Order_and_Referring_01_31_2022.csv", blocksize="10GB")

In [6]:
all_order_and_referring_physicians["NPI"] = all_order_and_referring_physicians["NPI"].astype(int)
cms_nppes_df["NPI"] = cms_nppes_df["NPI"].astype(int)

In [7]:
joined = cms_nppes_df.merge(all_order_and_referring_physicians, left_on="NPI", right_on="NPI", how="inner")

In [8]:
intersection_df = joined.compute()

distributed.worker - WARNING - Worker is at 84% memory usage. Pausing worker.  Process memory: 3.37 GiB -- Worker memory limit: 4.00 GiB
distributed.worker - WARNING - Worker is at 59% memory usage. Resuming worker. Process memory: 2.37 GiB -- Worker memory limit: 4.00 GiB

In [9]:
intersection_df.head()

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,...,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15,Certification Date,LAST_NAME,FIRST_NAME,PARTB,DME,HHA,PMD
0,1588667638,1.0,NaN,NaN,NaN,PILCHER,WILLIAM,C,DR.,NaN,...,NaN,NaN,NaN,NaN,PILCHER,WILLIAM,Y,Y,Y,Y
1,1306849450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SMITSON,HAROLD,N,Y,N,Y
2,1215930367,1.0,NaN,NaN,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,...,NaN,NaN,NaN,NaN,GRESSOT,LAURENT,Y,Y,Y,Y
3,1932102084,1.0,NaN,NaN,NaN,ADUSUMILLI,RAVI,K,NaN,NaN,...,NaN,NaN,NaN,NaN,ADUSUMILLI,RAVI,Y,Y,Y,Y
4,1750384806,1.0,NaN,NaN,NaN,BISBEE,ROBERT,NaN,DR.,NaN,...,NaN,NaN,NaN,NaN,BISBEE,ROBERT,Y,Y,Y,Y

In [10]:
intersection_df.shape

(1695713, 336)

In [15]:
intersection_df.to_csv("../data/intersection_df_nppes_pecos_02032022.csv", index=False)

In [19]:
intersection_df[['Provider First Line Business Mailing Address',
       'Provider Second Line Business Mailing Address',
       'Provider Business Mailing Address City Name',
       'Provider Business Mailing Address State Name',
       'Provider Business Mailing Address Postal Code',
       'Provider Business Mailing Address Country Code (If outside U.S.)',
       'Provider Business Mailing Address Telephone Number',
       'Provider Business Mailing Address Fax Number']].sample(100)

,Provider First Line Business Mailing Address,Provider Second Line Business Mailing Address,Provider Business Mailing Address City Name,Provider Business Mailing Address State Name,Provider Business Mailing Address Postal Code,Provider Business Mailing Address Country Code (If outside U.S.),Provider Business Mailing Address Telephone Number,Provider Business Mailing Address Fax Number
292,1000 E MAIN ST,NaN,MEDFORD,OR,975047667,US,5417733863,5417762892
6929,2500 METROHEALTH DR,NaN,CLEVELAND,OH,441091900,US,2167784486,NaN
7430,6900 PECOS RD,NaN,NORTH LAS VEGAS,NV,890864400,US,7027919000,7022246985
2708,24654 N LAKE PLEASANT PKWY,STE 103-433,PEORIA,AZ,853831359,US,6232257980,6232257736
2387,2605 E CREEKS EDGE DR,NaN,BLOOMINGTON,IN,474018368,US,8123332663,8123499206
...,...,...,...,...,...,...,...,...
6206,6399 SAN IGNACIO AVE STE 120,NaN,SAN JOSE,CA,951191215,US,6122277749,4089047730
1188,1804 EMBARCADERO RD STE 100,NaN,PALO ALTO,CA,943033318,US,NaN,NaN
1239,310 15TH AVE E,NaN,SEATTLE,WA,981125103,US,2063263000,2063262785
3478,4700 ALLIANCE BLVD,SUITE 400,PLANO,TX,750935323,US,4698146631,4698143110
3727,50 IRVING ST NW,MENTAL HEALTH,WASHINGTON,DC,204220001,US,2027458000,NaN

In [26]:
print(f"This is the percent of the NPPES providers that share information with PECOS: {(1695713 / 7147730) * 100}%")

This is the percent of the NPPES providers that share information with PECOS: 23.723797625260048%

In [25]:
# The most representative states according to NPPES
intersection_df["Provider Business Mailing Address State Name"].value_counts()[:10]

CA    163009
NY    131657
TX    108497
FL    101920
PA     80747
OH     70137
IL     69604
MI     63877
MA     59776
NC     55307
Name: Provider Business Mailing Address State Name, dtype: int64

In [28]:
# non - US registered business addresses from NPPES. Is this permissible?
intersection_df["Provider Business Mailing Address State Name"].value_counts()[-20:]

NORTH SHORE     1
NEWFOUNDLAND    1
SHOUF           1
TRINIDAD        1
ST. GEORGE      1
VIRGINIA        1
INDIANA         1
SLASK           1
MIDDLESEX       1
HAWAII          1
P.R.            1
NONTHABURI      1
ILOILO          1
ISTANBUL        1
SIEM REAP       1
VOJVODINA       1
NAIROBI         1
DHAKA           1
TAMILNADU       1
SAITAMA         1
Name: Provider Business Mailing Address State Name, dtype: int64